# Generated by Django 3.2.7 on 2021-09-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Id', models.CharField(max_length=15)),
                ('Time_in', models.DateTimeField(max_length=20)),
                ('Time_out', models.DateTimeField(blank=True, max_length=20, null=True)),
                ('Status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Weekoff', 'Weekoff')], default='Present', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_ID', models.CharField(max_length=15)),
                ('From', models.DateField(blank=True, max_length=20, null=True)),
                ('To', models.DateField(blank=True, max_length=20, null=True)),
                ('Basic', models.IntegerField()),
                ('HRA', models.IntegerField()),
                ('Other_Allowance', models.IntegerField()),
                ('LTA', models.IntegerField()),
                ('Incentive', models.IntegerField()),
                ('Bonus', models.IntegerField()),
                ('EPF', models.IntegerField()),
                ('ESI', models.IntegerField()),
                ('TDS', models.IntegerField()),
                ('Other_Deductions', models.IntegerField()),
                ('Annual_Leaves', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees_Detail',
            fields=[
                ('Employee_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Employee_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=10)),
                ('Date_Of_Birth', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(choices=[('Select', 'Select'), ('Male', 'Male'), ('Female', 'Female')], default='Select', max_length=20)),
                ('Address_Line_1', models.CharField(blank=True, max_length=50)),
                ('Address_Line_2', models.CharField(blank=True, max_length=50)),
                ('PAN_Card_Number', models.CharField(blank=True, max_length=10)),
                ('Bank_Acount_Name', models.CharField(blank=True, max_length=30)),
                ('Bank_Account_Number', models.CharField(blank=True, max_length=30)),
                ('Passport_Size_Image', models.ImageField(null=True, upload_to='images')),
                ('Reference_1_Name', models.CharField(blank=True, max_length=20)),
                ('Reference_1_Phone_number', models.CharField(blank=True, max_length=20)),
                ('Reference_2_Name', models.CharField(blank=True, max_length=20)),
                ('Reference_2_Phone_number', models.CharField(blank=True, max_length=20)),
                ('Spouse_Or_Husband_Or_Father_Name', models.CharField(blank=True, max_length=30)),
                ('Spouse_Or_Husband_Or_Father_Date_Of_Birth', models.CharField(blank=True, max_length=30)),
                ('Spouse_Or_Husband_Or_Father_Phone_Number', models.CharField(blank=True, max_length=10)),
                ('Child_1_If_any', models.CharField(blank=True, max_length=20)),
                ('Child_2_If_any', models.CharField(blank=True, max_length=20)),
                ('Education_Qualification_1', models.CharField(blank=True, max_length=30)),
                ('Education_Qualification_2', models.CharField(blank=True, max_length=30)),
                ('Experience', models.CharField(blank=True, max_length=50)),
                ('Last_Place_Of_Work', models.CharField(blank=True, max_length=20)),
                ('Previous_Postion', models.CharField(blank=True, max_length=50)),
                ('Department_Type', models.CharField(choices=[('Select', 'Select'), ('Sales', 'Sales'), ('Service', 'Service'), ('Both', 'Both'), ('Admin', 'Admin')], default='Select', max_length=20)),
                ('Department', models.CharField(choices=[('Select', 'Select'), ('HR', 'HR'), ('Gate', 'Gate'), ('IT', 'IT'), ('Accounts', 'Accounts'), ('Warranty', 'Warranty'), ('Warranty', 'Warranty'), ('Insurance', 'Insurance'), ('Customer Care', 'Customer Care')], default='Select', max_length=20)),
                ('Role', models.CharField(choices=[('Select', 'Select'), ('GM', 'GM'), ('CFO', 'CFO'), ('VP', 'VP'), ('CEO', 'CEO'), ('Manager', 'Manager'), ('Sales Manager', 'Sales Manager'), ('Service Manager', 'Service Manager'), ('Customer Care Manager', 'Customer Care Manager'), ('Executive', 'Executive'), ('Accounts Officer', 'Accounts Officer'), ('Accounts Head', 'Accounts Head')], default='Select', max_length=30)),
                ('Weekoff', models.CharField(default='Sunday', max_length=10)),
                ('Join_Date', models.DateField(blank=True, max_length=15, null=True)),
                ('Left_Date', models.DateField(blank=True, max_length=15, null=True)),
                ('Leave_Per_Month', models.IntegerField(null=True)),
                ('Leave_Balance', models.IntegerField(null=True)),
                ('Joining_Salary', models.IntegerField(null=True)),
            ],
        ),
    ]
