# Generated by Django 3.2.7 on 2021-09-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_attendance',
            name='Employee_Id',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employee_payroll',
            name='Employee_ID',
            field=models.IntegerField(max_length=15),
        ),
    ]
