# Generated by Django 3.2.7 on 2021-09-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR_Management', '0002_auto_20210917_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_attendance',
            name='Employee_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_Management.employees_detail'),
        ),
        migrations.AlterField(
            model_name='employee_payroll',
            name='Employee_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_Management.employees_detail'),
        ),
    ]
